name: bart-calc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipywidgets
  - notebook
  - voila
  - pandas
  - numpy
  - folium
  - pip
  - pip:
      - openrouteservice
